version: "3.8"

services:
  seascape-js:
    build:
      context: .
    container_name: "seascape-js"
    volumes:
      - type: bind
        source: ./
        target: /home/node/app/
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file: 
      - ./.env
networks:
  net:
